language: csharp
mono: none
dotnet: 2.2.103
dist: bionic
install:
 - dotnet restore
script:
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover tests/moment.net.Tests.csproj
after_success:
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
 - ./tools/csmacnz.Coveralls --opencover -i ./tests/coverage.opencover.xml --useRelativePaths